-- Migration file: Create classes and teacher_class_assignments tables
-- Note: id columns are set to text to accommodate the current mock ID format generated by the frontend.

create table if not exists public.classes (
  id text primary key,
  name text not null,
  academic_year text not null,
  class_teacher_id text,
  institution_id uuid references public.institutions(id) on delete cascade,
  student_count integer default 0,
  created_at timestamptz default now() not null
);

create table if not exists public.teacher_class_assignments (
  id text primary key,
  teacher_id text not null,
  class_id text references public.classes(id) on delete cascade,
  subject_id text,
  role text not null check (role in ('class_teacher', 'subject_teacher', 'both')),
  created_at timestamptz default now() not null
);

-- Note: Since the users table isn't explicitly defined in migrations,
-- we'll attempt to add class_id if a public.users table exists.
do $$ 
begin
  if exists (select from pg_tables where schemaname = 'public' and tablename = 'users') then
    execute 'alter table public.users add column if not exists class_id text';
  end if;
end $$;

-- Enable RLS
alter table public.classes enable row level security;
alter table public.teacher_class_assignments enable row level security;

-- Policies for classes:
-- 1. Anyone can read classes (in a real app, this might be restricted to members of the institution)
create policy "classes_read_all" on public.classes for select using (true);
create policy "classes_insert_all" on public.classes for insert with check (true);
create policy "classes_update_all" on public.classes for update using (true);
create policy "classes_delete_all" on public.classes for delete using (true);

-- Policies for teacher_class_assignments:
create policy "assignments_read_all" on public.teacher_class_assignments for select using (true);
create policy "assignments_insert_all" on public.teacher_class_assignments for insert with check (true);
create policy "assignments_update_all" on public.teacher_class_assignments for update using (true);
create policy "assignments_delete_all" on public.teacher_class_assignments for delete using (true);
